version: "3.9"
services:
  autodb:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AUTODB_CHROMA_DIR=/data/chroma
      - AUTODB_SQLITE_URL=sqlite:////data/autodb.sqlite
    volumes:
      - ./data:/data
